FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /app
COPY ./MarketAPI/*.csproj ./
RUN dotnet restore MarketAPI.csproj
COPY ./MarketAPI/. ./
RUN dotnet publish MarketAPI.csproj -c Debug -o dev/

RUN apt update && \
    apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

FROM microsoft/dotnet:2.2-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=0 /app/dev .
ENTRYPOINT ["dotnet", "MarketAPI.dll"]